default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  timeout: 5000
  username: developer
  password: developer

development:
  <<: *default
  database: nils_2_skills_dev

test:
  <<: *default
  database: nils_2_skills_test

production:
  <<: *default
  database: nils_2_skills
